version: 2.1

orbs:
  python: circleci/python@0.2.1
  aws-cli: circleci/aws-cli@2.0
  serverless: circleci/serverless-framework@1.0.1
jobs:
  aws-check:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: aws cloudformation deploy --template-file .\proj1Stack.json --stack-name cr-proj1-test --region us-west-1 
workflows:
  main:
    jobs:
      - aws-check