version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  aws-check:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: aws cloudformation deploy --template-file proj1Stack.json --stack-name cr-proj1-test
workflows:
  main:
    jobs:
      - aws-check